spring:
  application:
    name: product-server
server:
  port: 7002
  servlet:
    context-path: /product
eureka:
  client:
    service-url:
    #defaultZone ����ǲ�����ʾ�ģ��˴���Ҫ�Լ�д
    #ʵ��������Ӧ����service-url,��������Ǹ�map��key-value����ʽ����key��defaultZone��ʱ����ܱ���������������û����ʾ��
    #�����Լ�����Ҫдһ��defaultZone��
      defaultZone: http://localhost:5060/eureka/eureka
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:7070/eureka/eureka



logging:
  config: classpath:logback-dev.xml
